knp_lab_rest_api:
    resource: "@KnpLabRestApiBundle/Controller"
    type:     annotation
    prefix: /api

lab_rest:
    resource: "@LabRestBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
  type: rest
  resource: LabRestBundle\Controller\DefaultController
