<?php

namespace KnpLabRestApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProgrammerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammerRepository extends EntityRepository
{
}
